services:
  postgres:
    container_name: postgres
    image: postgres:17
    environment:
      POSTGRES_USER: gs1
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: ruleengine
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5432
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:9.4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - postgres
    restart: unless-stopped

  ruleengine:
    container_name: ruleengine
    image: mahshtayeh227/ruleengine
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 8000:8000
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: